public class UmlCanvasService 
{
	public static ToolingApi.SymbolTable symbolTable(String className)
	{
		return null;
	}

	public static ToolingApi.ContainerAsyncRequest compile(String className)
	{
		return null;
	}

	public static ToolingAPI.ContainerAsyncRequest containerAsyncRequest(String asyncRequestId)
	{
		return null;
	}

	public static ToolingApi.SymbolTable symbolTable(String asyncRequestId, String className)
	{
		return null;
	}
}